/**
 * Builds the full chart-library manifest consumed by the composer and the
 * client-side renderers. Extracted from src/pages/library.json.ts so the
 * manifest can be partitioned into two prerendered payloads without
 * duplicating ~400 lines of synthesis logic:
 *
 *   - /library.json      (lean): visible-by-default sources + hint cards +
 *                                charts + metros/countries lookups +
 *                                tagCountsByGeo. ~2 MB.
 *   - /library-geo.json  (geo):  the hidden-by-default geo source block
 *                                (CD / state / metro / county / country),
 *                                ~37 MB, lazy-loaded by the client only when
 *                                a geo chip is engaged or a >=4-char query
 *                                unlocks them. See src/lib/library-loader.ts.
 *
 * `buildLibraryManifest()` is memoized at module scope so the two endpoints
 * that slice it (library.json.ts + library-geo.json.ts) share one build pass
 * within a single prerender — the heavy work (getCollection + tag synthesis
 * over ~30k sources) runs once, not twice.
 *
 * The build-time empty-selector invariants + the hint synthesis run over the
 * FULL source set inside this builder (before the lean/geo partition), so the
 * split can't smuggle an empty chip dropdown past the guard.
 */
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";
import { getCollection } from "astro:content";
import {
  METRO_TAG,
  metroTagsFor,
  parseMetroSourceId,
} from "./geographic-regions";
import {
  CD_TAG,
  STATE_TAG,
  parseCdSourceId,
  parseStateSourceId,
} from "./congressional-districts";
import { COUNTRY_TAG, parseCountrySourceId } from "./countries";
import { COUNTY_TAG, parseCountySourceId, parseQcewSourceId } from "./county-sources";
import { isVisibleChart } from "./resolve-dashboard";
import { synthesizeSourceHints } from "./source-hints";
import { computeTagCountsByGeo } from "./tag-counts-precompute";
import quarantined from "./quarantined-sources.json";

// Sources auto-hidden because their data file is missing on disk —
// generated by scripts/audit-source-data.mjs in prebuild. See the
// skip in the source loop below.
const QUARANTINED_SOURCE_IDS: Record<string, string> = quarantined.ids;

/**
 * The umbrella geo tags whose presence makes a source hidden-by-default in
 * the picker (it surfaces only behind a geo chip or a >=4-char query). This
 * is the partition predicate for the lean/geo split and MUST match the
 * SourcePicker's GEO_UMBRELLA_TAGS set (which includes COUNTY_TAG).
 */
const GEO_UMBRELLA_TAGS: ReadonlyArray<string> = [
  CD_TAG,
  STATE_TAG,
  METRO_TAG,
  COUNTRY_TAG,
  COUNTY_TAG,
];

/** True if a source with these tags is hidden-by-default (belongs in the
 *  lazy-loaded /library-geo block rather than the lean /library.json).
 *  Hint cards are never geo-hidden — callers keep `kind:"hint"` in lean. */
export function isGeoHidden(tags: ReadonlyArray<string> | undefined): boolean {
  if (!tags) return false;
  for (const t of GEO_UMBRELLA_TAGS) if (tags.includes(t)) return true;
  return false;
}

/** Drop the umbrella geo tags so an UNPLACEABLE geo source (one that lands in
 *  the residual `misc` bucket — declares a geo tag but no entity parser places
 *  it) can be emitted into the lean manifest as a plain, visible source rather
 *  than silently hidden-and-unreachable. Per-entity tags (metro:<cbsa>,
 *  country-specific:<code>) are kept so e.g. a national `country-specific:USA`
 *  series still appears under the United States chip. */
export function stripGeoUmbrellaTags(tags: ReadonlyArray<string>): string[] {
  const umbrellas: ReadonlyArray<string> = GEO_UMBRELLA_TAGS;
  return tags.filter((t) => !umbrellas.includes(t));
}

/**
 * Sources permitted to land in the residual `misc` bucket — geo-hidden (they
 * declare us-state etc.) but no entity parser can place them under a chip.
 * The bucket should trend to EMPTY; every entry is a KNOWN mis-tag (these are
 * national/aggregate series wrongly carrying `us-state`) tracked for a pipeline
 * fix. They are still surfaced — emitted into the lean manifest with their
 * umbrella tag stripped (see stripGeoUmbrellaTags) — so nothing is invisible.
 *
 * The guard in computeGeoBuckets THROWS if a source lands in misc that isn't
 * listed here: that's the "flag when misc grows" alarm. To clear it, teach
 * parseStateSourceId / the bucketing its id pattern (preferred — then it
 * buckets + surfaces via a chip), or add it here with a reason.
 */
const ALLOWED_GEO_MISC_IDS: ReadonlySet<string> = new Set([
  // USDA NASS "Other States" aggregates: NASS's residual for states it doesn't
  // publish individually. Not one state (can't bucket under the state chip)
  // and not a national total — genuinely `misc`. Their description notes which
  // states ARE reported separately (see pipelines/usda_nass.py). They're still
  // surfaced (the lean endpoint emits them de-geo'd).
  // (The BEA `_united_states` national series that used to sit here were
  // re-tagged national in pipelines/bea.py — they're visible national sources
  // now, not misc.)
  "usda_nass/corn_production_ot",
  "usda_nass/corn_yield_ot",
  "usda_nass/soybeans_price_ot",
  "usda_nass/soybeans_production_ot",
  "usda_nass/soybeans_yield_ot",
]);

/**
 * Lightweight CBSA-code → display-name lookup, parsed from the
 * pipelines/_crosswalks/cbsa_metro.csv that drives the metro pipelines.
 * Shipped in the manifest so the composer's "Metro area" chip can label
 * each CBSA without a second fetch. Read once per build.
 */
async function loadMetroLookup(): Promise<Record<string, { shortName: string; name: string }>> {
  // Two candidate paths: the dev-mode path (cwd is the repo root when
  // `astro dev` runs from the project root) and the build-time path
  // derived from import.meta.url (cwd may differ during prerender).
  // Try cwd first because Vite's SSR loader sometimes rewrites
  // import.meta.url into a virtual path that fileURLToPath can't
  // resolve.
  const candidates = [
    resolve(process.cwd(), "pipelines", "_crosswalks", "cbsa_metro.csv"),
  ];
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    candidates.push(
      resolve(here, "..", "..", "pipelines", "_crosswalks", "cbsa_metro.csv"),
    );
  } catch {
    // import.meta.url not file-URL-resolvable (some bundler contexts);
    // the cwd candidate is sufficient.
  }
  const out: Record<string, { shortName: string; name: string }> = {};
  let text: string | null = null;
  for (const p of candidates) {
    try {
      text = await readFile(p, "utf-8");
      break;
    } catch {
      // Try next candidate.
    }
  }
  if (text === null) {
    // Crosswalk missing — composer will hide the chip. Not an error.
    return out;
  }
  const lines = text.split(/\r?\n/);
  if (lines.length < 2) return out;
  const header = lines[0].split(",");
  const codeIdx = header.indexOf("cbsa_code");
  const shortIdx = header.indexOf("short_name");
  const nameIdx = header.indexOf("name");
  if (codeIdx < 0 || shortIdx < 0 || nameIdx < 0) return out;
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim()) continue;
    // Cheap CSV split: handle one quoted field. The crosswalk only
    // quotes the `name` column (which contains commas). Other columns
    // are alphanumeric / pipe-separated and don't need a full parser.
    const cells = splitMaybeQuoted(line);
    const code = cells[codeIdx]?.trim();
    if (!code) continue;
    out[code] = {
      shortName: cells[shortIdx]?.trim() ?? code,
      name: cells[nameIdx]?.trim() ?? code,
    };
  }
  return out;
}

function splitMaybeQuoted(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let inQuote = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      inQuote = !inQuote;
      continue;
    }
    if (ch === "," && !inQuote) {
      out.push(cur);
      cur = "";
      continue;
    }
    cur += ch;
  }
  out.push(cur);
  return out;
}

/**
 * Date-range manifest: `{ "data/<rel>.json": [firstT, lastT] }`, built by
 * pipelines/build_summaries.py during its existing all-data pass. Read once
 * here so the source loop below doesn't open ~25k data files at build time
 * (that per-source read was a ~6.5-minute prerender bottleneck). Uses the
 * same cwd / import.meta.url candidate dance as loadMetroLookup because the
 * prerender cwd is unreliable. Missing/unreadable → {} (graceful: sources
 * simply report no coverage range).
 */
async function loadDateIndex(): Promise<Record<string, [string, string]>> {
  const candidates = [
    resolve(process.cwd(), "public", "data", "source_index.json"),
  ];
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    candidates.push(
      resolve(here, "..", "..", "public", "data", "source_index.json"),
    );
  } catch {
    // import.meta.url not file-URL-resolvable in this bundler context.
  }
  for (const p of candidates) {
    try {
      return JSON.parse(await readFile(p, "utf-8"));
    } catch {
      // Try next candidate.
    }
  }
  return {};
}

export interface LibraryManifest {
  charts: unknown[];
  sources: Record<string, { kind?: string; tags?: string[] } & Record<string, unknown>>;
  metros: Record<string, { shortName: string; name: string }>;
  metroTag: string;
  countries: Record<string, { name: string }>;
  countryTag: string;
  tagCountsByGeo: Record<string, Record<string, number>>;
}

let cached: Promise<LibraryManifest> | null = null;

/** Build (and memoize) the complete library manifest. */
export function buildLibraryManifest(): Promise<LibraryManifest> {
  if (!cached) cached = compute();
  return cached;
}

async function compute(): Promise<LibraryManifest> {
  const [chartsCol, sourcesCol, metroLookup, dateIndex] = await Promise.all([
    getCollection("charts"),
    getCollection("sources"),
    loadMetroLookup(),
    loadDateIndex(),
  ]);

  // Restrict the manifest's metro table to CBSAs that actually have at
  // least one source on disk — keeps the composer's metro dropdown from
  // listing metros the pipelines haven't populated yet.
  const metrosInUse = new Set<string>();
  // Same idea for countries / regions: code → display name, sorted by
  // display name in the manifest emission below.
  const countriesInUse = new Map<string, string>();

  const sources: Record<string, unknown> = {};
  for (const s of sourcesCol) {
    // YAML-declared `hidden: true` removes the source from the
    // composer's discovery surface. Existing dashboards that pin
    // this source ID via their state_json still resolve correctly —
    // resolve-dashboard.ts walks the content collection directly,
    // not library.json. See src/content/config.ts for the schema
    // field's rationale (mostly: yahoo/<ticker> raw-price sources
    // suppressed in favor of yahoo_marketcap/<ticker>_mc).
    if ((s.data as { hidden?: boolean }).hidden) continue;
    // Quarantined: generated by scripts/audit-source-data.mjs in
    // prebuild when a source's data file is missing on disk (the
    // usaspending/metro_* orphan class). Same effect as hidden:true —
    // dropped from discovery so the picker can't offer a tile that
    // will never load — but automatic, loudly ::warning::-flagged in
    // build logs, and self-healing once the data lands. Saved
    // dashboards pinning the id still resolve via resolve-dashboard.
    if (s.id in QUARANTINED_SOURCE_IDS) continue;
    // First / last observation dates, read from the precomputed
    // source_index.json manifest (built by pipelines/build_summaries.py in
    // its existing all-data pass) rather than by opening this source's data
    // file here. Opening all ~25k files at build was a ~6.5-minute prerender
    // bottleneck. A missing entry leaves the dates undefined (graceful — the
    // composer just omits the coverage range for that source).
    const range = dateIndex[s.data.dataFile];
    const firstObservation = range?.[0];
    const lastObservation = range?.[1];
    // Per-source `searchText`: lowercased haystack the composer's source-
    // picker greps against. Includes name/shortName/description (so a
    // ticker like "XOM" or a pipeline-style ID matches even when typing
    // a common name), the source-id itself, and the tags string (so
    // typing "macro" matches every source tagged macro). Same idea as
    // the chart-level searchText below.
    //
    // Three classes of synthetic tags get injected here (rather than
    // mutating thousands of source YAMLs) so the composer's geo-region
    // chips can filter without each YAML having to declare them:
    //   - CD_TAG ("congressional-district") for usaspending/district_*
    //     and acs_cd/* — surfaced under the "States & districts" chip.
    //   - STATE_TAG ("us-state") for usaspending/state_*, fred/state_*,
    //     bls/state_* — surfaced under the same chip via "Statewide".
    //   - METRO_TAG ("metro") + per-CBSA metro:<cbsa> for the metro
    //     pipelines — surfaced under the "Metro area" chip. metroTagsFor
    //     returns both the umbrella and per-CBSA tag in one call.
    // metrosInUse tracks which CBSAs actually appear in the source
    // universe so the manifest only ships those in the metro lookup.
    const declaredTags = s.data.tags ?? [];
    const synthetics: string[] = [];
    if (parseCdSourceId(s.id)) synthetics.push(CD_TAG);
    if (parseStateSourceId(s.id)) synthetics.push(STATE_TAG);
    if (parseCountySourceId(s.id)) synthetics.push(COUNTY_TAG);
    // QCEW jurisdiction sources (bls/qcew_*) reuse the COUNTY_TAG
    // hide-by-default flag (8 county-equivalents + the Washington MSA);
    // without this they leak into the default list tagged `us`.
    if (parseQcewSourceId(s.id)) synthetics.push(COUNTY_TAG);
    const metroExtra = metroTagsFor(s.id);
    if (metroExtra.length > 0) synthetics.push(...metroExtra);
    const parsedMetro = parseMetroSourceId(s.id);
    if (parsedMetro) metrosInUse.add(parsedMetro.cbsa);
    // Country / region tagging: non-US country sources + regional
    // aggregates get hidden by default behind the "Countries & regions"
    // chip. Per-country tag (`country:<CODE>`) lets the drill-down
    // filter to a single country.
    const parsedCountry = parseCountrySourceId(s.id);
    if (parsedCountry) {
      synthetics.push(COUNTRY_TAG);
      synthetics.push(`${COUNTRY_TAG}:${parsedCountry.code}`);
      countriesInUse.set(parsedCountry.code, parsedCountry.name);
    }
    // Special-case: US-wide national sources get `country-specific:USA`
    // but NOT the umbrella COUNTRY_TAG. The asymmetry is intentional —
    // COUNTRY_TAG hides a source from the default list (the chip is how
    // you opt back in), but US-wide sources should stay visible by
    // default since the audience is US-focused. The per-country tag
    // makes them ALSO surface when the user picks "United States" from
    // the chip, which yields exactly the national-US slice.
    //
    // Identification: the `us` topical tag AND no other geo class
    // already attached (CD / state / metro / foreign-country) AND
    // no sub-national pattern in the source ID. State / CD / metro
    // US sources stay out of the US national slice on purpose —
    // picking "United States" means national, not "all the US sub-
    // aggregates too". The ID-pattern check catches county-level BLS
    // data (e.g. bls/county_unemployment_alexandria_va) that's tagged
    // `us` but represents a sub-national geography with no
    // synthetic-tag parser.
    const isAlreadyGeo =
      synthetics.includes(CD_TAG) ||
      synthetics.includes(STATE_TAG) ||
      synthetics.includes(COUNTY_TAG) ||
      synthetics.includes(COUNTRY_TAG) ||
      metroExtra.length > 0;
    const isSubNationalById = /\/(county|city|zip)_/.test(s.id);
    // US tagging, by strong default. Every US-subnational geography
    // (congressional district, state, county/QCEW jurisdiction, metro CBSA)
    // is US soil; tag it `us` even when the YAML didn't declare it, so the
    // "exclude US" topical filter is comprehensive for foreign users.
    // Covers usaspending (878 district/state sources), bls state/qcew, zillow
    // metros, and any acs_*/fred state source missing the declared tag.
    const hasUsGeo =
      synthetics.includes(CD_TAG) ||
      synthetics.includes(STATE_TAG) ||
      synthetics.includes(COUNTY_TAG) ||
      metroExtra.length > 0;
    // US-national series filed under a country pipeline's USA entity, which
    // parseCountrySourceId deliberately leaves untagged so they stay visible
    // by default (oecd/usa_*, owid_*/*_united_states, worldbank_gdp_raw/usa,
    // countries_gdp/usa). These ARE US economy numbers, so tag them `us` too.
    const isUsNational =
      /^oecd\/usa_/.test(s.id) ||
      /_united_states$/.test(s.id) ||
      /^(?:worldbank_gdp_raw|countries_gdp)\/usa$/.test(s.id);
    // Every USAspending source is US federal spending — including the
    // territories (state_as/gu/mp/pr/vi), whose codes parseStateSourceId
    // doesn't recognize, so they'd otherwise miss the geo-based us tag above.
    const isUsProvider = /^usaspending\//.test(s.id);
    if ((hasUsGeo || isUsNational || isUsProvider) && !declaredTags.includes("us")) {
      synthetics.push("us");
    }
    const hasUs = declaredTags.includes("us") || synthetics.includes("us");
    if (!isAlreadyGeo && !isSubNationalById && hasUs) {
      synthetics.push(`${COUNTRY_TAG}:USA`);
      countriesInUse.set("USA", "United States");
    }
    const tagsList =
      synthetics.length > 0
        ? [...new Set([...declaredTags, ...synthetics])].sort()
        : declaredTags;
    const sourceSearchText = [
      s.data.name,
      s.data.shortName,
      s.data.description,
      s.id,
      tagsList.join(" "),
    ]
      .filter(Boolean)
      .join(" ")
      .toLowerCase();
    sources[s.id] = {
      id: s.id,
      name: s.data.name,
      shortName: s.data.shortName,
      description: s.data.description,
      kind: s.data.kind,
      pipeline: s.data.pipeline,
      dataFile: s.data.dataFile,
      supportedDeltas: s.data.supportedDeltas,
      unit: s.data.unit,
      formatting: s.data.formatting,
      emphasis: s.data.emphasis,
      provenance: s.data.provenance,
      // Rate→(numerator, denominator, scale) link so the composer can offer
      // "× <denominator>" to rebuild a total and substitute the exact count.
      // Undefined for non-derived sources (JSON.stringify drops it).
      derivedFrom: (s.data as { derivedFrom?: unknown }).derivedFrom,
      // One-click combine suggestion (e.g. NASS price × quantity → value).
      // Undefined for sources without it (JSON.stringify drops it).
      combineHint: (s.data as { combineHint?: unknown }).combineHint,
      firstObservation,
      lastObservation,
      tags: tagsList,
      searchText: sourceSearchText,
      unitClass: s.data.unitClass,
      // Editorial annotations a chart inherits when this source is added
      // as a chart (composer) — e.g. FEC redistricting boundary notes.
      // Undefined for sources without it (JSON.stringify drops it).
      defaultAnnotations: s.data.defaultAnnotations,
    };
  }

  const charts = chartsCol
    // Hide charts tagged deprecated=true without an alias. Aliased ones still
    // expose the redirect so saved dashboards can resolve transparently.
    .filter(isVisibleChart)
    // Hide single-source pregenerated charts (sources.length === 1 AND no
    // chart-level op) from the composer's Pregenerated tab. They're pure
    // wrappers around their underlying source — users get the same chart
    // by clicking the source in the Sources tab, which goes through
    // addSourceAsChart and produces an inline single-series chart. Keeping
    // them surfaces redundant cards in the picker.
    //
    // The chart YAMLs stay on disk because the preset dashboard pages
    // (/us-macro/, /stocks/, /tech/, /va-08/) resolve chart IDs via
    // getEntry("charts", id) directly, NOT through this manifest. So the
    // preset pages keep rendering; only the composer's Pregenerated tab
    // is affected. Charts with an `op` set (e.g. 10Y-2Y diff over 2
    // sources) stay visible; multi-source charts always stay visible.
    .filter((c) => {
      const srcCount = (c.data.sources ?? []).length;
      const hasOp = !!(c.data as { op?: string }).op;
      return srcCount > 1 || hasOp;
    })
    .map((c) => {
      // Build a single concatenated `searchText` field on the server to keep
      // client-side search cheap and consistent. Includes title, id, tags,
      // and each linked source's name/shortName/description.
      const sourceText = (c.data.sources ?? [])
        .map((sid) => {
          const s = (sources as Record<string, { name?: string; shortName?: string; description?: string }>)[sid];
          if (!s) return "";
          return [s.name, s.shortName, s.description].filter(Boolean).join(" ");
        })
        .join(" ");
      const searchText = [
        c.data.title,
        c.id,
        (c.data.tags ?? []).join(" "),
        c.data.blurb ?? "",
        sourceText,
      ]
        .filter(Boolean)
        .join(" ")
        .toLowerCase();
      return {
        id: c.id,
        title: c.data.title,
        tags: c.data.tags ?? [],
        sources: c.data.sources,
        render: c.data.render,
        defaultDelta: c.data.defaultDelta,
        normalize: c.data.normalize,
        // Carry chart-level `op` so the composer's Pregenerated tab can
        // render op-collapsed charts (10Y-2Y spread, future spread/ratio
        // charts) the same way the published dashboards do, and so
        // promote-library-to-inline preserves the op.
        op: (c.data as { op?: "divide" | "sum" | "diff" }).op,
        seriesLabels: c.data.seriesLabels,
        blurb: c.data.blurb,
        emphasis: c.data.emphasis,
        deprecated: c.data.deprecated,
        aliasOf: c.data.aliasOf,
        searchText,
      };
    });

  // Trim the metro lookup to entries that appear in at least one
  // source. Sorted by short name so the composer dropdown is
  // alphabetical out of the box.
  const metros: Record<string, { shortName: string; name: string }> = {};
  const usedCodes = [...metrosInUse].sort((a, b) => {
    const an = metroLookup[a]?.shortName ?? a;
    const bn = metroLookup[b]?.shortName ?? b;
    return an.localeCompare(bn);
  });
  for (const code of usedCodes) {
    metros[code] = metroLookup[code] ?? { shortName: code, name: code };
  }

  // Trim the country lookup to entries actually present in this manifest,
  // sorted alphabetically by name so the composer dropdown reads naturally.
  const countries: Record<string, { name: string }> = {};
  const usedCountryCodes = [...countriesInUse.keys()].sort((a, b) =>
    (countriesInUse.get(a) ?? a).localeCompare(countriesInUse.get(b) ?? b),
  );
  for (const code of usedCountryCodes) {
    countries[code] = { name: countriesInUse.get(code) ?? code };
  }

  // Build-time invariant check: every UI selector option must have at
  // least one source carrying the matching per-entity tag. By
  // construction the lookups + tags are populated in lockstep, so a
  // violation indicates a parser bug or a stale entity slug. Better to
  // fail the build loudly than to ship a chip dropdown where picking
  // "Europe" yields zero sources.
  const emptyEntities: string[] = [];
  const checkEntity = (label: string, code: string, tag: string) => {
    let count = 0;
    for (const sid of Object.keys(sources)) {
      const tags = (sources[sid] as { tags?: string[] }).tags ?? [];
      if (tags.includes(tag)) {
        count += 1;
        break;
      }
    }
    if (count === 0) emptyEntities.push(`${label} '${code}' (tag '${tag}') has zero matching sources`);
  };
  for (const code of usedCodes) {
    checkEntity("metro CBSA", code, `${METRO_TAG}:${code}`);
  }
  for (const code of usedCountryCodes) {
    checkEntity("country/region", code, `${COUNTRY_TAG}:${code}`);
  }

  // Topical-tag pill check: a tag that only appears on hidden sources
  // (sources tagged CD / STATE / METRO / COUNTRY, which the default
  // list filters out) renders as a zero-count pill in the composer.
  // Catches things like `africa` / `europe` that used to live on
  // worldbank_extended regional sources — those regions are surfaced
  // via the Regions and countries chip, the topical tag added nothing.
  // Mirrors the visibility filter in renderTagFiltersSources +
  // filteredSources.
  const isHiddenByDefault = (tags: string[]): boolean =>
    tags.includes(CD_TAG) ||
    tags.includes(STATE_TAG) ||
    tags.includes(METRO_TAG) ||
    tags.includes(COUNTRY_TAG);
  const isGeoSynthetic = (t: string): boolean =>
    t === CD_TAG ||
    t === STATE_TAG ||
    t === METRO_TAG ||
    t === COUNTRY_TAG ||
    t.startsWith(`${METRO_TAG}:`) ||
    t.startsWith(`${COUNTRY_TAG}:`);
  const tagsSeenAnywhere = new Set<string>();
  const tagsWithVisibleSource = new Set<string>();
  for (const sid of Object.keys(sources)) {
    const tags = (sources[sid] as { tags?: string[] }).tags ?? [];
    const visible = !isHiddenByDefault(tags);
    for (const t of tags) {
      if (isGeoSynthetic(t)) continue;
      tagsSeenAnywhere.add(t);
      if (visible) tagsWithVisibleSource.add(t);
    }
  }
  const zeroCountPills: string[] = [];
  for (const t of tagsSeenAnywhere) {
    if (!tagsWithVisibleSource.has(t)) zeroCountPills.push(t);
  }
  if (zeroCountPills.length > 0) {
    emptyEntities.push(
      ...zeroCountPills.map(
        (t) =>
          `topical tag pill '${t}' would render with count 0 ` +
          `(no source carrying that tag is visible in the default list — ` +
          `every source with this tag is hidden behind a geo chip)`,
      ),
    );
  }

  if (emptyEntities.length > 0) {
    // Throw, don't console.error — Astro propagates the throw and the
    // prerender step fails the build. This is intentional: shipping an
    // empty selector option is a worse UX than a build failure.
    const msg =
      `library.json build failed: ${emptyEntities.length} UI selector ` +
      `option${emptyEntities.length === 1 ? "" : "s"} would render empty.\n` +
      emptyEntities.map((e) => `  - ${e}`).join("\n");
    throw new Error(msg);
  }

  // Synthetic "see also" hint cards — surface in the composer's
  // source search when the query matches a series we cover at a
  // geo level beyond national (metro / state / county / CD /
  // country / tract / block group). Improves discoverability for
  // first-time visitors who don't know to engage a chip first.
  // See src/lib/source-hints.ts for the rationale + format.
  type SourceMetaSlice = { name?: string; tags?: string[] };
  const hintsList = synthesizeSourceHints(
    Object.entries(sources).map(([id, s]) => {
      const meta = s as SourceMetaSlice;
      return {
        id,
        name: meta.name ?? id,
        tags: meta.tags ?? [],
      };
    }),
  );
  // Inject hints into the sources map keyed by their synthetic id
  // (`_hint/<level>`). They share the map with real sources so the
  // composer's existing search/filter loop processes them uniformly;
  // the composer's renderer dispatches on `kind: "hint"` to render
  // an info card instead of a click-to-add-as-chart button.
  for (const h of hintsList) {
    (sources as Record<string, unknown>)[h.id] = h;
  }

  // Build-time precomputed tag-count contingency table for the
  // SourcePicker's topical tag-chip strip. Computed over the FULL source
  // set (incl. geo) so the chip counts stay correct even though the geo
  // sources ship in a separate lazy-loaded payload — the picker reads
  // tagCountsByGeo[<bucketKey>] from the lean manifest and never needs the
  // geo block just to render accurate counts. See
  // src/lib/tag-counts-precompute.ts for the bucket-key conventions.
  const tagCountsByGeo = computeTagCountsByGeo(
    sources as Record<string, { tags?: string[]; kind?: string }>,
  );

  return {
    charts,
    sources: sources as LibraryManifest["sources"],
    metros,
    metroTag: METRO_TAG,
    countries,
    countryTag: COUNTRY_TAG,
    tagCountsByGeo,
  };
}

type GeoSourceMap = Record<string, LibraryManifest["sources"][string]>;
export interface GeoBuckets {
  /** 2-letter state → its CD + statewide sources. */
  state: Record<string, GeoSourceMap>;
  /** CBSA code → its metro sources. */
  metro: Record<string, GeoSourceMap>;
  /** Foreign country / region code → its sources. */
  country: Record<string, GeoSourceMap>;
  /** All us-county / QCEW-jurisdiction sources (small; one file). */
  county: GeoSourceMap;
  /** Geo-hidden sources no entity parser claimed (should be ~empty; one file
   *  so the client's missing-id fallback never 404s). */
  misc: GeoSourceMap;
}

let geoCache: Promise<GeoBuckets> | null = null;

/**
 * Partition the geo-hidden sources into per-entity buckets, one file each, so
 * the composer only fetches the slice the user actually drilled into (a metro
 * pick is ~20 KB, not the 37 MB whole-block). Memoized alongside the manifest.
 *
 * Bucketing keys MUST match the picker's filter predicates (src/lib/
 * source-filters.ts) so the file loaded for a selection contains exactly the
 * sources that selection surfaces:
 *   - metro by the `metro:<cbsa>` tag    (passesMetroFilter reads that tag)
 *   - country by `country-specific:<code>` + COUNTRY_TAG, i.e. foreign only
 *                                          (passesCountryFilter reads the tag)
 *   - state by parsed state from the id  (passesCdFilter uses parseCdSourceId)
 *   - county umbrella tag → the county singleton (passesCountyFilter)
 * The client's id→entity resolver (src/lib/geo-entity.ts) mirrors this.
 */
export function buildGeoBuckets(): Promise<GeoBuckets> {
  if (!geoCache) geoCache = computeGeoBuckets();
  return geoCache;
}

async function computeGeoBuckets(): Promise<GeoBuckets> {
  const manifest = await buildLibraryManifest();
  const buckets: GeoBuckets = {
    state: {},
    metro: {},
    country: {},
    county: {},
    misc: {},
  };
  for (const [id, s] of Object.entries(manifest.sources)) {
    if (s.kind === "hint") continue;
    const tags = s.tags ?? [];
    if (!isGeoHidden(tags)) continue;
    const metroTag = tags.find((t) => t.startsWith(METRO_TAG + ":"));
    if (metroTag) {
      const cbsa = metroTag.slice(METRO_TAG.length + 1);
      (buckets.metro[cbsa] ??= {})[id] = s;
      continue;
    }
    const ctryTag = tags.find((t) => t.startsWith(COUNTRY_TAG + ":"));
    if (tags.includes(COUNTRY_TAG) && ctryTag) {
      const code = ctryTag.slice(COUNTRY_TAG.length + 1);
      (buckets.country[code] ??= {})[id] = s;
      continue;
    }
    if (tags.includes(COUNTY_TAG)) {
      buckets.county[id] = s;
      continue;
    }
    const st = parseCdSourceId(id)?.state ?? parseStateSourceId(id)?.state ?? null;
    if (st) {
      (buckets.state[st] ??= {})[id] = s;
      continue;
    }
    buckets.misc[id] = s;
  }
  // Flag growth: a geo-hidden source that no parser could place is unreachable
  // via any chip. We still surface it (the lean endpoint emits misc sources
  // de-geo'd), but a NEW one almost always means a mis-tag or an unhandled id
  // convention — fail the build so it gets a parser rule (preferred) or an
  // explicit ALLOWED_GEO_MISC_IDS entry rather than slipping in unnoticed.
  const unexpected = Object.keys(buckets.misc)
    .filter((id) => !ALLOWED_GEO_MISC_IDS.has(id))
    .sort();
  if (unexpected.length > 0) {
    throw new Error(
      `buildGeoBuckets: ${unexpected.length} geo-hidden source(s) fell into ` +
        `the residual 'misc' bucket — they declare a geo tag (us-state etc.) ` +
        `but no entity parser placed them, so they can't surface under a chip. ` +
        `Teach parseStateSourceId / the bucketing their id pattern (preferred), ` +
        `or add to ALLOWED_GEO_MISC_IDS in build-library-manifest.ts with a ` +
        `reason:\n` + unexpected.map((id) => `  - ${id}`).join("\n"),
    );
  }
  return buckets;
}
