// AUTO-GENERATED by scripts/gen-source-count.mjs (runs in prebuild).
// Do not edit by hand -- change the rounding/format in that script.
// Count of source YAMLs under src/content/sources as of the last build.

/** Exact source count at build time. */
export const SOURCE_COUNT = 34719;

/** Marketing figure, floored to the nearest 1,000 with a "+", e.g. "34,000+". */
export const SOURCE_COUNT_DISPLAY = "34,000+";
