#!/usr/bin/env python3
"""
Audit the Census state-government-finance YAMLs against the live
``govsstatefin`` AGG_DESC_LABEL attribute.

These 255 YAMLs (src/content/sources/census_govfin/) are generated by
pipelines/_scaffold_census_govfin.py from a 5-row AGGREGATES table, so
the labels are "correct by construction" — the only real risk is the
code→meaning mapping in that table being wrong (e.g. someone adds a
sixth aggregate and pastes the wrong SF#### code, or Census renumbers
a line code). The generic token-overlap heuristic the other provider
audits use is too weak here: every expenditure label contains the word
"expenditure", so a welfare↔highway swap would pass. Instead this audit
pins each code to a discriminating keyword that must appear in BOTH the
provider's official label AND every YAML name carrying that code, and
forbids keywords that would indicate an off-by-one code shift.

Usage:
  python scripts/audit_census_govfin.py
  python scripts/audit_census_govfin.py --strict
  python scripts/audit_census_govfin.py --json --no-cache
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import yaml as pyyaml
except ImportError:
    print("Install PyYAML: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

# govsstatefin (unlike the Census metadata endpoints) requires an API
# key. Load .env so local runs pick up CENSUS_API_KEY; in CI the
# data-refresh workflow already exports it. A committed label cache
# (scripts/_census_govfin_audit_cache.json) lets the audit run offline
# from cache when no key is present; --no-cache forces a live re-fetch.
try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:  # noqa: BLE001
    pass

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "src" / "content" / "sources" / "census_govfin"
CACHE_PATH = ROOT / "scripts" / "_census_govfin_audit_cache.json"
API = "https://api.census.gov/data/timeseries/govsstatefin"

CODE_RE = re.compile(r"\b(SF\d{4})\b")

# code: (label_must_include, label_must_exclude, name_must_include) — all
# lowercase substring checks. label_* is matched against the live
# AGG_DESC_LABEL; name_must_include against the YAML `name`. Keep this in
# lockstep with pipelines/census_govfin.py's AGGREGATES.
EXPECTED: dict[str, tuple[list[str], list[str], str]] = {
    "SF0001": (["revenue"],             ["expenditure"],         "revenue"),
    "SF0132": (["total expenditure"],   ["general", "welfare"],  "total expenditure"),
    "SF0133": (["general expenditure"], ["welfare", "highway"],  "general expenditure"),
    "SF0353": (["public welfare"],      [],                      "welfare"),
    "SF0281": (["highways"],            [],                      "highway"),
}


def fetch_labels(api_key: str | None) -> dict[str, str]:
    """Return {SF####: official AGG_DESC_LABEL}. One call (CA, recent
    year) carries every line code's label."""
    url = (f"{API}?get=AMOUNT,AGG_DESC,AGG_DESC_LABEL,CATEGORY"
           f"&for=state:06&YEAR=2022")
    if api_key:
        url += f"&key={api_key}"
    try:
        r = subprocess.run(
            ["curl", "-sS", "-L", "--max-time", "30", url],
            capture_output=True, check=True,
        )
        rows = json.loads(r.stdout.decode("utf-8", errors="replace"))
    except Exception as e:  # noqa: BLE001
        print(f"[!] fetch failed: {e}", file=sys.stderr)
        return {}
    if not isinstance(rows, list) or len(rows) < 2:
        return {}
    h = rows[0]
    di, li = h.index("AGG_DESC"), h.index("AGG_DESC_LABEL")
    return {r[di]: r[li] for r in rows[1:]}


def read_yamls() -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for p in sorted(SOURCE_DIR.glob("*.yaml")):
        try:
            data = pyyaml.safe_load(p.read_text(encoding="utf-8"))
        except Exception as e:  # noqa: BLE001
            print(f"  skipping {p.name}: {e}", file=sys.stderr)
            continue
        series = (data.get("provenance") or {}).get("series", "")
        m = CODE_RE.search(series or "")
        out.append({
            "file": str(p.relative_to(ROOT)),
            "name": data.get("name", ""),
            "code": m.group(1) if m else None,
        })
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true")
    ap.add_argument("--no-cache", action="store_true")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    rows = read_yamls()
    print(f"Auditing {len(rows)} census_govfin YAMLs...", file=sys.stderr)

    labels: dict[str, str] = {}
    if not args.no_cache and CACHE_PATH.exists():
        try:
            labels = json.loads(CACHE_PATH.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            labels = {}
    if not labels:
        labels = fetch_labels(os.environ.get("CENSUS_API_KEY") or None)
        if labels:
            CACHE_PATH.write_text(json.dumps(labels, indent=2, sort_keys=True),
                                  encoding="utf-8")

    findings: list[dict[str, Any]] = []
    for r in rows:
        code, name = r["code"], r["name"].lower()
        notes: list[str] = []
        bad = False
        if not code:
            bad = True
            notes.append("no SF#### code in provenance.series")
        elif code not in EXPECTED:
            bad = True
            notes.append(f"code {code} not in EXPECTED map — unaudited aggregate")
        else:
            inc, exc, name_kw = EXPECTED[code]
            official = (labels.get(code) or "").lower()
            if not official:
                # No label means the fetch failed AND the cache lacked
                # this code — we can't actually audit, so fail loudly
                # rather than report a hollow pass (the original bug:
                # an empty fetch silently reported 0 mismatches).
                bad = True
                notes.append(f"no label for {code} — need CENSUS_API_KEY "
                             f"or a seeded cache to audit")
            else:
                for kw in inc:
                    if kw not in official:
                        bad = True
                        notes.append(f"official label missing '{kw}': '{labels.get(code)}'")
                for kw in exc:
                    if kw in official:
                        bad = True
                        notes.append(f"official label unexpectedly contains '{kw}': '{labels.get(code)}'")
            if name_kw not in name:
                bad = True
                notes.append(f"YAML name missing '{name_kw}'")
        if bad:
            findings.append({"file": r["file"], "code": code,
                             "name": r["name"], "official": labels.get(code or ""),
                             "notes": notes})

    if args.json:
        print(json.dumps({"total": len(rows), "mismatches": len(findings),
                          "findings": findings}, indent=2))
    else:
        print(f"\nTotal: {len(rows)}  Mismatches: {len(findings)}\n")
        for f in findings:
            print(f"[!] {f['file']}  ({f['code']})")
            print(f"    yaml:     {f['name']}")
            print(f"    official: {f['official']}")
            for n in f["notes"]:
                print(f"    note:     {n}")
            print()
        if not findings:
            print("OK: every YAML's code maps to the expected official label.")

    return 1 if (args.strict and findings) else 0


if __name__ == "__main__":
    sys.exit(main())
