#!/usr/bin/env python3
"""
Audit the NAEP source YAMLs (src/content/sources/naep/).

Generated by pipelines/_scaffold_naep.py from a fixed 4-metric table.
The risk is a scaffolder mismap pairing a metric id with the wrong
subject/grade words. This local audit pins each id's metric token
(mathg4 / mathg8 / readg4 / readg8) to the subject + grade that must
appear in BOTH the YAML name and the provenance series. No network call
needed — NAEP metric definitions are fixed.

Usage:
  python scripts/audit_naep.py
  python scripts/audit_naep.py --strict --json
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

try:
    import yaml as pyyaml
except ImportError:
    print("Install PyYAML: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "src" / "content" / "sources" / "naep"

# metric token -> (subject word, grade phrase) that must appear in the
# name + series. Keep in lockstep with pipelines/naep_scores.py METRICS.
METRIC_CHECK: dict[str, tuple[str, str]] = {
    "mathg4": ("math", "grade 4"),
    "mathg8": ("math", "grade 8"),
    "readg4": ("reading", "grade 4"),
    "readg8": ("reading", "grade 8"),
}
ID_RE = re.compile(r"^(?:us|state)_(mathg4|mathg8|readg4|readg8)(?:_[a-z]{2})?$")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    findings: list[dict[str, Any]] = []
    total = 0
    for p in sorted(SOURCE_DIR.glob("*.yaml")):
        total += 1
        try:
            data = pyyaml.safe_load(p.read_text(encoding="utf-8"))
        except Exception as e:  # noqa: BLE001
            findings.append({"file": p.name, "notes": [f"unreadable: {e}"]})
            continue
        sid = p.stem
        name = (data.get("name") or "").lower()
        series = ((data.get("provenance") or {}).get("series") or "").lower()
        m = ID_RE.match(sid)
        notes: list[str] = []
        if not m:
            notes.append(f"id doesn't match NAEP metric pattern: {sid}")
        else:
            subj, grade = METRIC_CHECK[m.group(1)]
            for field, txt in (("name", name), ("series", series)):
                if subj not in txt:
                    notes.append(f"{field} missing subject '{subj}'")
                if grade not in txt:
                    notes.append(f"{field} missing '{grade}'")
            # cross-subject guard: a math metric must not say "reading"
            other = "reading" if subj == "math" else "math"
            if other in name:
                notes.append(f"name for a {subj} metric also says '{other}'")
        if notes:
            findings.append({"file": p.name, "name": data.get("name"), "notes": notes})

    if args.json:
        print(json.dumps({"total": total, "mismatches": len(findings),
                          "findings": findings}, indent=2))
    else:
        print(f"\nTotal: {total}  Mismatches: {len(findings)}\n")
        for f in findings[:40]:
            print(f"[!] {f['file']}: {f['notes']}")
        if not findings:
            print("OK: every NAEP metric id matches its subject + grade.")
    return 1 if (args.strict and findings) else 0


if __name__ == "__main__":
    sys.exit(main())
